#    Carpenter
#    A cross-platform dotnet (.NET) build process helper.
#
#    Copyright © 2015-2022 Nosnitor Corporation, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT

#
# Pipeline definition for Azure Pipelines.
#


parameters:
  # The build type if a build is manually run. This value gets overridden by automated builds.
- name: buildType
  displayName: 'Build Type'
  type: string
  default: CI
  values:
  - CI
  - Prerelease
  - Release

  # The prerelease label. This value is only used if buildType is Prerelease.
- name: prereleaseLabel
  displayName: 'Prerelease Label'
  type: string
  default: alpha
  values:
  - alpha
  - beta
  - RC


# Default name for the build, prior to build versioning
# $(Build.BuildId) is the default value used when YAML cannot be parsed
name: $(Build.BuildId)


# Infrastructure variables
variables:
- group: Infrastructure
- group: Infrastructure-Vault


# Dependent resources
resources:
  repositories:
  # Carpenter is used for build/release pipeline.
  - repository: Carpenter
    type: github
    name: suent/carpenter-azure-pipelines
    endpoint: suent


# Use pipeline template
stages:
- template: templates/carpenter-default.yml@Carpenter
  parameters:
    pipelineVersion: 1
    buildType: ${{ parameters.buildType }}
    project: Carpenter
    defaultPoolType: Private
    defaultPoolName: Default
    defaultPoolDemands:
    - Agent.OS -equals Linux
    - Agent.OSArchitecture -equals X64
    versionType: SemVer
    prereleaseLabel: ${{ parameters.prereleaseLabel }}
    incrementVersionOnRelease: true
